//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public string Name { get; set; }
        public int PaymentId { get; set; }
        public string Description { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
